[package]
name = "xsscan"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
reqwest = "0.12.4"
regex = "1.10.4"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
mockito = "1.4.0"